### ISSUE TITLE
I can't run HTML5Setup.sh successful

### ISSUE THREAD

**Issue by KGTyrael** [UnrealEngineHTML5/Documentation#11]
Under Windows 10 1909, when I run HTML5Setup.sh, it always show that./emsdk: line 18: /c/Users/kyleh/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
I have already setup python3.8 and cmake. And I also add python to the Path. I have tried to delete the emsdk folder, but it doesn't work.
![75816655-8f7aec80-5dd0-11ea-8aa1-48ae90220b8f](https://user-images.githubusercontent.com/43983032/76075972-e5ba7c00-5fd8-11ea-9633-13c49ecf37f9.png)

**Comment by nickshinpho** [comment]
this looks like you just double clicked on `HTML5Setup.sh` file --  which is not in the instructions from:

- https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.0.building.UE4.Editor.md#on-windows

please try **opening** the `git-bash` command prompt window **first**, and then **type** out the command as instructed above.

we will look at your python3 issues afterwards...

**Comment by KGTyrael** [comment]
> this looks like you just double clicked on `HTML5Setup.sh` file -- which is not in the instructions from:
> 
> * https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.0.building.UE4.Editor.md#on-windows
> 
> please try **opening** the `git-bash` command prompt window **first**, and then **type** out the command as instructed above.
> 
> we will look at your python3 issues afterwards...

Thank you. I have already tried this way by type command in git-bash. But it looks like doesn't work.
 
I tried to uninstall Python3.8 and install Python3.7.It succeeded. 

I even thought that I didn't configure the Python to cause the problem.But when my friend repeats it on his computer which installed Python3.8, the same problem has arisen. When he install Phthon3.7 and uninstall Python3.8 again. Wow, only in this way can the operation succeed.

**Comment by nickshinpho** [comment]
fantastic -- that's good investigation information.  i will upgrade locally and test this detail.  should be interesting to see what different behavior this causes.

**Comment by nickshinpho** [comment]
@KGTyrael , may i ask what python3.8 installer did you use?  when i'm installing from python's download page, it's asking to install to:

- `C:\Users\nickshin\AppData\Local\Programs\Python\Python38-32`

- note: ...\\**Programs\Python**\\...

but, i see on your screenshot, that's it's asking to install to:

- ...\\**Microsoft\WindowsApp**\\...

i am not familiar with that path...

**Comment by Siphonn** [comment]
\Microsoft\WindowsApp\ is the path for the Microsoft Store I believe. I was having trouble running HTML5Setup.sh due to this path. Once the \Microsoft\WindowsApp\ path was removed from environment variables, HTML5Setup.sh ran properly.

**Comment by darkwere** [comment]
Hi! Need a help with this situation:

darkw@TSUNAMI MINGW64 /a/ue4-r424-html5 (4.24-html5)
$ cd Engine/Platforms/HTML5

darkw@TSUNAMI MINGW64 /a/ue4-r424-html5/Engine/Platforms/HTML5 (4.24-html5)
$ ./HTML5Setup.sh
Writing .emscripten configuration file to user home directory A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate/
Warning: The SDK/tool 'node-12.9.1-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'python-3.7.4-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'java-8.152-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'sdk-releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
Backing up old Emscripten configuration file in A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten.old
The Emscripten configuration file A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten has been rewritten with the following contents:

NODE_JS = 'node'
TEMP_DIR = 'C:/Users/darkw/AppData/Local/Temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += /a/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0

Setting environment variables:
EMSDK = A:/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0
EM_CONFIG = A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten

No tools/SDKs found to activate! Usage:
   emsdk activate tool/sdk1 [tool/sdk2] [...]

darkw@TSUNAMI MINGW64 /a/ue4-r424-html5/Engine/Platforms/HTML5 (4.24-html5)
$

**Comment by programmerBlack** [comment]
> Hi! Need a help with this situation:
> 
> darkw@TSUNAMI MINGW64 /a/ue4-r424-html5 (4.24-html5)
> $ cd Engine/Platforms/HTML5
> 
> darkw@TSUNAMI MINGW64 /a/ue4-r424-html5/Engine/Platforms/HTML5 (4.24-html5)
> $ ./HTML5Setup.sh
> Writing .emscripten configuration file to user home directory A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate/
> Warning: The SDK/tool 'node-12.9.1-64bit' cannot be activated since it is not installed! Skipping this tool...
> Warning: The SDK/tool 'python-3.7.4-64bit' cannot be activated since it is not installed! Skipping this tool...
> Warning: The SDK/tool 'java-8.152-64bit' cannot be activated since it is not installed! Skipping this tool...
> Warning: The SDK/tool 'releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
> Warning: The SDK/tool 'sdk-releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
> Backing up old Emscripten configuration file in A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate.emscripten.old
> The Emscripten configuration file A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate.emscripten has been rewritten with the following contents:
> 
> NODE_JS = 'node'
> TEMP_DIR = 'C:/Users/darkw/AppData/Local/Temp'
> COMPILER_ENGINE = NODE_JS
> JS_ENGINES = [NODE_JS]
> 
> Adding directories to PATH:
> PATH += /a/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0
> 
> Setting environment variables:
> EMSDK = A:/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0
> EM_CONFIG = A:\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate.emscripten
> 
> No tools/SDKs found to activate! Usage:
> emsdk activate tool/sdk1 [tool/sdk2] [...]
> 
> darkw@TSUNAMI MINGW64 /a/ue4-r424-html5/Engine/Platforms/HTML5 (4.24-html5)
> $

I'm having the same exact issue after removing WindowsApps/ path from the environment variables.

**Comment by Siphonn** [comment]
I removed the WindowsApps/ path from environment variables because it was stopping the version python I had installed.
Do you have a version of python installed? If you do, you may need to add the path for the python.exe to the Environment variables.

If not, install Python (3.8.2 worked for me). During the install there is an option to 'Add Python to Path'.

https://user-images.githubusercontent.com/36541593/77494601-0dfe0380-6e3e-11ea-99db-a8b88a07639e.png

You may need to delete the emsdk folder in /Engine/Platforms/HTML5/Build
Then use git bash to run ./HTML5Setup.sh again

Hopefully this will help.

**Comment by darkwere** [comment]
i have python 3.7.3 installed and remove WindowsApps path from PATH environment variable

**Comment by programmerBlack** [comment]
My python version is 3.7.0

![image](https://user-images.githubusercontent.com/5554663/77588022-3e798800-6ea6-11ea-9891-6635e8791d21.png)

**Comment by programmerBlack** [comment]
Removing the emsdk folder did help me make some prorgress. Now it goes through installing node, Java, and other libraries.

But fails with an obscure python error. Attached is the log, error is at the end.

[HTML5Setup_Console_Output.txt](https://github.com/UnrealEngineHTML5/Documentation/files/4383828/HTML5Setup_Console_Output.txt)

**Comment by Siphonn** [comment]
The errors might have something to do with Cmake. Do you have CMake 3.12 or above?
Cmake also needs to be added to environment variable PATH.

**Comment by darkwere** [comment]
I have CMake 3.17 successfully installed. 
Now I have passed HTML5Setup, but have no HTML5 packaging options in UE4Editor.
And I also had a warnings that python2.7 is missing while packaging a projects.
Does python 2.7 really needed?

**Comment by VerrroS** [comment]
I also have a problem running HTML5Setup.sh. It runs for almost 2 hours and then I get a "Success!"
but also this warnings

WARNING: emsdk-1.39.0 (windows) python PATH NOT FOUND -- skipping EPIC patches here
WARNING: emsdk-1.39.0-fastcomp (windows) python PATH NOT FOUND -- skipping EPIC patches here

Eventough added python to PATH and when I do the "python --version" command I get my python version. I cannot generate the project file

**Comment by Siphonn** [comment]
@darkwere 
Had the same problem myself. A change needs to be made in the HTML5SDKInfo.cs file. 

Here is a link the solution that help me:
https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600106852

@VerrroS 
A version of python is installed in the emsdk folder during HTMLSetup.sh (\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\3.7.4_64bit). I'm not sure if this also needs to be added to PATH but doing so may remove your warning.

**Comment by VerrroS** [comment]
Thanks, I added these to my PATH but I still get the warning.. any other ideas?

**Comment by Siphonn** [comment]
Perhaps the order of the PATH?
Maybe emsdk\emsdk-1.39.0\python\3.7.4_64bit needs to be before (or after) you other python path so it will be called first.

**Comment by bigjcr** [comment]
Can somebody confirm whether these warnings are relevant or not please? 

WARNING: emsdk-1.39.0 (windows) python PATH NOT FOUND -- skipping EPIC patches here
WARNING: emsdk-1.39.0-fastcomp (windows) python PATH NOT FOUND -- skipping EPIC patches here

I was able to generate a package of an empty blueprint project, but soon after launch it throws errors. 
HTMLLaunchHelper.exe is missing in the package folder (nowhere to be found) and I don't know if this file is necessary for the build to work or not, or if it's creation depends on these warnings.

**Comment by VerrroS** [comment]
@bigjcr
Had the same Warning- I was able to built the Unreal Editor, but I couln't package my project for HTML

**Comment by bigjcr** [comment]
@VerrroS 
I made exactly this https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600106852 and I was able to package the project for HTML, also I added the project at 
Engine/Platforms/HTML5/Source/Programs/HTML5/HTML5LaunchHelper
to the solution and now HTML5LaunchHelper.exe appears when I package.

The issues I had previously with my packaged project seem to be related to the new SunSky, disabling it removes all errors, but dynamic lighting seems to fail as well, it produces no errors but the sky looks pitch black.

**Comment by VerrroS** [comment]
@bigjcr
Nice, thanks I'll try this again. Can you tell me under what type did you add the project to the solution? 
![HTML5LAUNCHHELPER](https://user-images.githubusercontent.com/50030830/78771684-e015d480-7990-11ea-8d52-ad9e8ab74087.JPG)

**Comment by bigjcr** [comment]
@VerrroS 
![image](https://user-images.githubusercontent.com/10608970/78788116-f57b0680-7970-11ea-93de-3f421335bc2a.png)
I used the option Add existing project, it didn't ask me to choose a type.

**Comment by darkwere** [comment]
Well, finally, after 6th tries from scratch - I made it. I've tried all the recipes mentioned above, including  last one. Also, there is a problem with the last recipe - a missing UE4.ico file, that caused unsuccessful build of HTML5LaunchHelper util. All you need to do: copy UE4.ico file from /engine/Source/Programs/UnrealVS/Resources to Engine/Platforms/HTML5/Source/Programs/HTML5/HTML5LaunchHelper

**Comment by nickshinpho** [comment]
i will be using #21 to follow up on `HTML5LaunchHelper` progress

**Comment by LTorrao** [comment]
Hello, I am  having this same issue, but I am already at 4.24-html5, latest commit ( [https://github.com/UnrealEngineHTML5/UnrealEngine/commit/d637d639e41ee661d56edd456714519f5471755c](url) )

So, doing https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600106852 seems unnecessary, because there's:

`static string PYTHON_VER = "3.7.4-pywin32_64bit";
`

which corresponds exactly to what is in

`Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\`

Yet, when bash-running HTML5Setup.sh I still get, at the end:

```
WARNING: emsdk-1.39.0 (windows) python PATH NOT FOUND -- skipping EPIC patches here
WARNING: emsdk-1.39.0-fastcomp (windows) python PATH NOT FOUND -- skipping EPIC patches here
```

Even though I have specifically installed 3.7.4 in my windows machine after uninstalling any other pythons, I've added it to the path, and is the first in the path.

I am trying to fix this because I have previously ignored these warnings, but when I tried to package the HTML5 project, I would get the missing compiled PhysX libraries as mentioned in https://github.com/UnrealEngineHTML5/Documentation/issues/5#issuecomment-576014941.

Regarding what is said in this linked issue, I've already reformatted the drive where the source lives, and I have nothing else on that drive.

**Comment by nickshinpho** [comment]
@LTorrao - those warnings can be ignored (because those patches are for python2) -  I've already removed those warnings on my work-in-progress 4.25 & i forgot to checkin this correction for the 4.24-html branch (I'll put that fix in tomorrow morning.)

**Comment by LTorrao** [comment]
Thank you @nickshinpho 

So, the warnings are not the reason why the third party libraries are not compiling... I'm lost here :)

**Comment by nickshinpho** [comment]
correct @LTorrao, the warnings is not the reason for issue #5.

for the strange "No space left on device" issue when building the thirdparty libs -- can you post your "hard drive settings" to the question at:

- https://github.com/UnrealEngineHTML5/Documentation/issues/5#issuecomment-637209116

(and post that in #5)
thanks! ^_^

**Comment by ngoalongcang** [comment]
I has er
zsh: permission denied: ./HTML5Setup.sh
some one fix it?
