### ISSUE TITLE
The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5.

### ISSUE THREAD

**Issue by se8820726** [UnrealEngineHTML5/Documentation#19]
when building UE4 in visual studio 2019 , I gave this error:

`The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.`

how can I solve this problem ?

**Comment by AdemJensen** [comment]
I have the same issue too!!!!!!!
This problem has been bugging me for some time:
When compiling "UE4" in VS2019, it goes wrong at: [3463/3466] UE4Editor-StaticMeshEditorExtension.dll
```
1>  [3463/3466] UE4Editor-StaticMeshEditorExtension.dll
1>  Creating library E:\ue424-h5\Engine\Plugins\Enterprise\StaticMeshEditorExtension\Intermediate\Build\Win64\UE4Editor\Development\StaticMeshEditorExtension\UE4Editor-StaticMeshEditorExtension.suppressed.lib and object E:\ue424-h5\Engine\Plugins\Enterprise\StaticMeshEditorExtension\Intermediate\Build\Win64\UE4Editor\Development\StaticMeshEditorExtension\UE4Editor-StaticMeshEditorExtension.suppressed.exp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "UE4.vcxproj" -- FAILED.
```
The Error List is:

| Severity  |	Code |	Description |	Project |	File |	 Line |	Suppression State |
| ------- | ------- | ------- | ------- | ------- | ------- | ------- |
|Warning|	C4996|	'TBaseMulticastDelegate<void>::AddRaw::FDeprecationMsg_788::condition': Binding a delegate with a const object pointer and non-const function is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.|	UE4	|E:\ue424-h5\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl	|788	|
|Error|	C4800|	Implicit conversion from 'ADODB::_Connection *const ' to bool. Possible information loss	|UE4|	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h|	311	|
|Error|	C4800|	Implicit conversion from 'ADODB::_Recordset *const ' to bool. Possible information loss	|UE4	|C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h	|311	|
|Error|	MSB3075 |	The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.	|UE4	|C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets|	44	|

( PS. Really, really annoying, the build procedure took away 3 hours from my computer to proceed, it just fails at the final steps...
In my opinion, this appears to be the latest toolchain's fault? I tried to run the 3463 command manually in cmd, and here is what I got:

```
E:\ue424-h5>Engine\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild
Building UE4Editor and ShaderCompileWorker...
Using Visual Studio 2019 14.25.28614 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 4 actions with 12 processes...
  [1/4] ADOSupport.cpp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(311): error C4800: Implicit conversion from 'ADODB::_Recordset *const ' to bool. Possible information loss
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(311): note: consider using explicit cast or comparison to nullptr to avoid this warning
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(310): note: while compiling class template member function '_com_ptr_t<_com_IIID<ADODB::_Recordset,& _GUID_00001556_0000_0010_8000_00aa006d2ea4>>::operator bool(void) noexcept const'
  E:\ue424-h5\Engine\Plugins\Runtime\Database\ADOSupport\Source\ADOSupport\Private\ADOSupport.cpp(255): note: see reference to function template instantiation '_com_ptr_t<_com_IIID<ADODB::_Recordset,& _GUID_00001556_0000_0010_8000_00aa006d2ea4>>::operator bool(void) noexcept const' being compiled
  E:\ue424-h5\Engine\Plugins\Runtime\Database\ADOSupport\Intermediate\Build\Win64\UE4Editor\Development\ADOSupport\msado15.tli(1813): note: see reference to class template instantiation '_com_ptr_t<_com_IIID<ADODB::_Recordset,& _GUID_00001556_0000_0010_8000_00aa006d2ea4>>' being compiled
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(311): error C4800: Implicit conversion from 'ADODB::_Connection *const ' to bool. Possible information loss
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(311): note: consider using explicit cast or comparison to nullptr to avoid this warning
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\INCLUDE\comip.h(310): note: while compiling class template member function '_com_ptr_t<_com_IIID<ADODB::_Connection,& _GUID_00001550_0000_0010_8000_00aa006d2ea4>>::operator bool(void) noexcept const'
  E:\ue424-h5\Engine\Plugins\Runtime\Database\ADOSupport\Source\ADOSupport\Private\ADOSupport.cpp(328): note: see reference to function template instantiation '_com_ptr_t<_com_IIID<ADODB::_Connection,& _GUID_00001550_0000_0010_8000_00aa006d2ea4>>::operator bool(void) noexcept const' being compiled
  E:\ue424-h5\Engine\Plugins\Runtime\Database\ADOSupport\Intermediate\Build\Win64\UE4Editor\Development\ADOSupport\msado15.tli(1760): note: see reference to class template instantiation '_com_ptr_t<_com_IIID<ADODB::_Connection,& _GUID_00001550_0000_0010_8000_00aa006d2ea4>>' being compiled
```
Maybe using VS 2017 will be better?

**Comment by AdemJensen** [comment]
Yes, I have confirmed that the problem comes from the latest VS Toolchain. It won't be a problem if you use old ones.
You can download a VS 2017 to start building.
(PS. The official have made it clear that the support of VS 2019 is still in process.)
