### ISSUE TITLE
Win 10 HTML5 build are broken

### ISSUE THREAD

**Issue by Forux** [UnrealEngineHTML5/Documentation#2]
*** 
/d/unreal/UE_4.24-html/Engine/Platforms/HTML5 (4.2                                                                              4-html5)
$ ./HTML5Setup.sh
Writing .emscripten configuration file to user home directory D:\unreal\UE_4.24-                                                                              html\Engine\Platforms\HTML5\Intermediate/
Warning: The SDK/tool 'node-12.9.1-64bit' cannot be activated since it is not in                                                                              stalled! Skipping this tool...
Warning: The SDK/tool 'python-2.7.13.1-64bit' cannot be activated since it is no                                                                              t installed! Skipping this tool...
Warning: The SDK/tool 'java-8.152-64bit' cannot be activated since it is not ins                                                                              talled! Skipping this tool...
Warning: The SDK/tool 'releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb4                                                                              9-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'sdk-releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073                                                                              ceb49-64bit' cannot be activated since it is not installed! Skipping this tool..                                                                              .
Backing up old Emscripten configuration file in D:\unreal\UE_4.24-html\Engine\Pl                                                                              atforms\HTML5\Intermediate\.emscripten.old
The Emscripten configuration file D:\unreal\UE_4.24-html\Engine\Platforms\HTML5\                                                                              Intermediate\.emscripten has been rewritten with the following contents:

NODE_JS = 'node'
TEMP_DIR = 'c:/users/forux/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += /d/unreal/UE_4.24-html/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0

Setting environment variables:
EMSDK = D:/unreal/UE_4.24-html/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0
EM_CONFIG = D:\unreal\UE_4.24-html\Engine\Platforms\HTML5\Intermediate\.emscript                                                                              en

No tools/SDKs found to activate! Usage:
   emsdk activate tool/sdk1 [tool/sdk2] [...]
** NOTICE **: The default SDK changed from `fastcomp` to `upstream`.
If you have problems, or wish to revert back to fastcomp for some other reason
you can add `-fastcomp` to explicitly install that fastcomp-based
SDK, .e.g ./emsdk install latest-fastcomp.
***

To fix that now you need to go to D:/unreal/UE_4.24-html/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0 and manualy install emsdk tools

**Comment by kainino0x** [comment]
On first glance, this sounds similar to #1. Does the info there help you out?

**Comment by pavel663** [comment]
I have similar issue.

> $ ./HTML5Setup.sh                                                                                                       Writing .emscripten configuration file to user home directory C:\Users\Drkane/
Warning: The SDK/tool 'node-12.9.1-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'python-2.7.13.1-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'java-8.152-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'releases-upstream-8bb7b0bbbca74cc58741416cc955011f22ff5ccb-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'sdk-releases-upstream-8bb7b0bbbca74cc58741416cc955011f22ff5ccb-64bit' cannot be activated since it is not installed! Skipping this tool...
The Emscripten configuration file C:\Users\Drkane\.emscripten has been rewritten with the following contents:

> NODE_JS = 'node'
TEMP_DIR = 'C:/Users/Drkane/AppData/Local/Temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

> Adding directories to PATH:
PATH += /e/UE_Bin/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.4

> Setting environment variables:
EMSDK = E:/UE_Bin/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.4
EM_CONFIG = C:\Users\Drkane\.emscripten

> No tools/SDKs found to activate! Usage:
   emsdk activate tool/sdk1 [tool/sdk2] [...]

if
> To fix that now you need to go to D:/unreal/UE_4.24-html/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0 and manualy install emsdk tools

How install manualy?
I have 2 folders after upgrade emscripten:
1. emsdk-1.39.0
2. emsdk-1.39.4

And my concern is that "user home directory" is not equal "...\Engine\Platforms\HTML5\Intermediate/".

**Comment by pavel663** [comment]
I deleted everything and downloaded again. Now going without errors.

**Comment by nickshinpho** [comment]
@pavel663 $HOME has been temporarily redirected an intermediate path

- https://github.com/UnrealEngineHTML5/UnrealEngine/blob/4.24-html5/Engine/Platforms/HTML5/HTML5Setup.sh#L40-L53

note: this intermediate path is also used in UE4 when packaging for HTML5.
