### ISSUE TITLE
emsdk-1.39.0 (windows) python PATH NOT FOUND -- skipping epic patch here

### ISSUE THREAD

**Issue by violacambie** [UnrealEngineHTML5/Documentation#20]
I'm bumping into this warning at the end of ./HTML5Setup.sh .
What is it? How can I solve it?
I have python 3.7.4 and 2.7.13 installed

Many thanks

![image](https://user-images.githubusercontent.com/25077324/79909451-46810500-841d-11ea-9128-96715a6dc98a.png)

**Comment by nooxouille** [comment]
I am bumping this one up with the exact same error, after successfully running the HTML5Setup.sh.
Python version is 3.7.7 but the issue was also present with a newer version (latest 3.8 Python release).

![mintty_I9TcNlxQt0](https://user-images.githubusercontent.com/2682226/80109188-7d6e2c80-857d-11ea-856e-dbb34577098d.png)

![SystemPropertiesAdvanced_Yy34AP1KVa](https://user-images.githubusercontent.com/2682226/80109767-30d72100-857e-11ea-8763-4f39d5d8691b.png)

Because of the "success" from the bash, I moved forward. When I try to build a BP template to HTML5, a LaunchURL event happen, to this page : https://docs.unrealengine.com/en-US/Platforms/HTML5/GettingStarted/index.html

I am kinda lost, and I am not a UE user so I might be missing something ...

![IVUp7OGkwj](https://user-images.githubusercontent.com/2682226/80110657-32edaf80-857f-11ea-8726-7ede2de5cab4.gif)

**Comment by catrujillo91** [comment]
Hello i have python 3.8.2 installed but when i run the "GenerateProjectFiles" i get this error:
PYTHON NOT FOUND: C:\UnrealEngine-4.24-html5\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\2.7.13.1_64bit/python-2.7.13.amd64\python.exe
* PYTHON NOT FOUND: C:\UnrealEngine-4.24-html5\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\2.7.13.1_64bit/python-2.7.13.amd64\python.exe

**Comment by nickshinpho** [comment]
please see if this solution works for you:

- https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600106852
  - step 3

i will be checking in some fixes which will include that (which may be sometime next week)

**Comment by Akromha** [comment]
This solution worked for me !
