### ISSUE TITLE
no file to download

### ISSUE THREAD

**Issue by 1point3** [UnrealEngineHTML5/Documentation#35]
i have linked my epic games account, and logged in to git hub, but still getting 404 error

**Comment by nickshinpho** [comment]
if you are able to see

- https://github.com/EpicGames/UnrealEngine

and not

- https://github.com/UnrealEngineHTML5/UnrealEngine

then re-open.

otherwise, please see updated information at the bottom of:

- https://github.com/UnrealEngineHTML5/Documentation

**Comment by 1point3** [comment]
Hi thanks, I was now able to access it must have just taken time to allow me, is there a built version already I can get as I am a designer not a programmer.

 

Cheers

 

Martin

**Comment by nickshin** [comment]
if HTML5 was still a supported platform -- then yes -- pre-built binaries would have been available -- and would be pulled down from running: "Setup.bat" (on the same path of where the Engine folder is).

but, because HTML5 is not an officially supported platform -- this has to be built from the sources.

- yes, it is possible to have these binaries built and put on S3, dropbox, or where ever
  - but this would mean forcing people to a particular UE4 version, emscripten version and so on
  - and this is way beyond the resources i have available

also, the goal of the community supported fork -- is to get other people involved to get UE4 still working with HTML5 which means having more people learning how to develop for/on it.

maybe someday we'll get to the point where there's a lot more resources to make this possible again...

- but for now, there's way less people (than the fingers on one hand) who are able to do this
- however, i'm hopeful that this will grow over time
