### ISSUE TITLE
NODEJS NOT FOUND

### ISSUE THREAD

**Issue by adee-patel** [UnrealEngineHTML5/Documentation#97]
When building ShaderCompileWorker I keep getting this error in Visual Studio 2019:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		NODEJS NOT FOUND: C:\Users\<username>\ue4-4.24.3-html5\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\node\12.18.1_64bit\bin\node.exe	ShaderCompileWorker	C:\Users\<username>\ue4-4.24.3-html5\Engine\Intermediate\ProjectFiles\UnrealBuildTool	1	
`

![Screenshot 2021-06-10 214643](https://user-images.githubusercontent.com/82430394/121618764-64e8fc00-ca35-11eb-930c-a2b8ec26a0c3.png)

**Comment by adee-patel** [comment]
Just got this issue fixed if anyone need a solution please comment here. Happy to help.

**Comment by nrabhiram** [comment]
Hey, I'm facing a similar issue as well. Could you help me out?

**Comment by mika314** [comment]
What is the fix? I have this error.

**Comment by pepefeliblu** [comment]
> Just got this issue fixed if anyone need a solution please comment here. Happy to help.

Could you please share the fix? I am facing a similar error while trying to build the UnrealHeaderTool

**Comment by mika314** [comment]
Ok, I have figured out the fix. You may notice in the logs something like node is missing or not installed (I do not remember the exact wording). What you need to do, extract the version from the path and do a full search, you will find a reference to this version in one of `*.cs` files. You need to update the version to the correct version. The correct version you can just find as a directory name.

In my case I needed to update this file:
```
modified   Engine/Platforms/HTML5/Source/Programs/UnrealBuildTool/HTML5SDKInfo.cs
@@ -20,7 +20,7 @@ namespace UnrealBuildTool
 		// note: as of 1.39.18, emscripten fastcomp has been deprecated
 
 		static string SDKVersion = "1.39.18";
-		static string NODE_VER = "12.18.1_64bit";
+		static string NODE_VER = "14.15.5_64bit";
 		static string EMSDKTYPE = "upstream";
 
 		static string PYTHON_VER = "3.7.4-pywin32_64bit"; // Only used on Windows; other platforms use built-in Python.
```

**Comment by pepefeliblu** [comment]
> Ok, I have figured out the fix. You may notice in the logs something like node is missing or not installed (I do not remember the exact wording). What you need to do, extract the version from the path and do a full search, you will find a reference to this version in one of `*.cs` files. You need to update the version to the correct version. The correct version you can just find as a directory name.
> 
> In my case I needed to update this file:
> 
> ```
> modified   Engine/Platforms/HTML5/Source/Programs/UnrealBuildTool/HTML5SDKInfo.cs
> @@ -20,7 +20,7 @@ namespace UnrealBuildTool
>  		// note: as of 1.39.18, emscripten fastcomp has been deprecated
>  
>  		static string SDKVersion = "1.39.18";
> -		static string NODE_VER = "12.18.1_64bit";
> +		static string NODE_VER = "14.15.5_64bit";
>  		static string EMSDKTYPE = "upstream";
>  
>  		static string PYTHON_VER = "3.7.4-pywin32_64bit"; // Only used on Windows; other platforms use built-in Python.
> ```

I can corroborate the missing NODEJS issue. And this seems to be the reasonable solution if you are still trying to build the engine from scratch. 

I have opted to downgrade to Engine Version 4.23.1 because, when I finished the build, I was simply redirected to the UE4-HTML Docs. 

I will probably avoid the HTML package route and simply create native apps (desktop/mobile) instead. Why?:

- How am I going to keep updating my project version of the engine later on? This solution forces you to build the engine from the scratch and I am not savvy enough to even consider updating this later on the road at the current stage of my project. 

- UE4 Core engine has already moved this to a CE fully. Meaning that it wont bring it to UE5. 

- HTML package exports are simply way to heavy for a web app. WASM and data files can take up to a gigabyte. Transferring that from an static server S3. Will take time and is a very painful load for users.
